"""empty message

Revision ID: d4e731d25d07
Revises: 
Create Date: 2021-01-18 19:44:20.879456

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e731d25d07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('user_mark', sa.Enum('X_MARK', 'O_MARK', 'EMPTY_MARK', name='mark'), nullable=False),
    sa.Column('winner_mark', sa.Enum('X_MARK', 'O_MARK', 'EMPTY_MARK', name='mark'), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('win_rule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_started_at'), 'games', ['started_at'], unique=False)
    op.create_table('usertokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=36), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('gamemoves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('mark', sa.Enum('X_MARK', 'O_MARK', 'EMPTY_MARK', name='mark'), nullable=True),
    sa.Column('position', postgresql.ARRAY(sa.Integer(), as_tuple=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamemoves_created_at'), 'gamemoves', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gamemoves_created_at'), table_name='gamemoves')
    op.drop_table('gamemoves')
    op.drop_table('usertokens')
    op.drop_index(op.f('ix_games_started_at'), table_name='games')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
