version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tic_tac_toe
    ports:
      - "5435:5432"
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "5555:80"
  migrations:
    depends_on:
      - backend
      - db
    build: .
    command: alembic upgrade head
  web:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  app-db-data:
